from django.urls import path
from frontend import views
from frontend.views import (
    AddArticleView,
    BlogCategoriesCreateView,
    BlogCategoriesDeleteView,
    BlogCategoriesUpdateView,
    BlogDetailView,
    BlogView,
    DeleteArticleView,
    EditArticleView,
    FormationArmaturesCubeCreateView,
    FormationArmaturesCubeListView,
    GalleryCreateView, GalleryDeleteView,
    GalleryListView, GalleryUpdateView,
    JourneeUtilisateur2021CreateView, LicenceEtablissementListView,
    LicenceEtablissementView,
    LicenceEtudiantListView, LicenceEtudiantView,
    ListeArticleView,
    PresentationFromyoutubeListView,
    PresentationListView, PresentationView,
    PresentationViewYoutuber,
    VideoCreateView,
    VideoDeleteView,
    VideoListView,
    VideoUpdateView, VideoView, GalerieView,
    JU2022CreateView,
    TrainingView, JU2022PlusCreateView, JU2022PlusListView, BatimatView, BatimatListView
)

urlpatterns = [
    path('', views.accueil, name="accueil"),
    #     path('analytics-vincavuotoPndFncVtGEJUpaNMEqcMbE9D5aLS5aXg', views.accueil, name="accueil2"),
    path('contact/', views.contact, name='contact'),
    path('galerie/', GalerieView.as_view(), name='galerie'),
    path('video/', VideoView.as_view(), name='video'),
    path('licence/', views.licence, name='licence'),
    path('condition_licence_etudiant/', views.condition_licence_etudiant,
         name='condition_licence_etudiant'),
    path('condition_licence_educative/', views.condition_licence_educative,
         name='condition_licence_educative'),
    path('cookies_policy/', views.cookies_policy, name='cookies_policy'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('terms_and_conditions/', views.terms_and_conditions,
         name='terms_and_conditions'),
    path('formation/videos/', TrainingView.as_view(), name='training'),

    # logiciel et solution
    path('logiciel-et-solution/', views.logiciel_cao, name='logiciel_cao'),
    path('logiciel-et-solution/ingenierie-de-construction/',
         views.ing_de_construction, name='ing_de_construction'),
    path('logiciel-et-solution/construction-de-batiments/',
         views.construction_de_batiment, name='construction_de_batiment'),
    path('logiciel-et-solution/pieces-prefabriquees-structurelles/',
         views.pieces_pref_structurelles, name='pieces_pref_structurelles'),
    path('logiciel-et-solution/pieces-prefabriquees-unitisees/',
         views.pieces_pref_unitisees, name='pieces_pref_unitisees'),
    path('logiciel-et-solution/architecture-pour-les-ingenieurs-en-structure/',
         views.architecture_ing_en_structure, name='architecture_ing_en_structure'),
    path('logiciel-et-solution/bim-modelisation-des-informations-du-batiment/',
         views.bim, name='bim'),
    path('logiciel-et-solution/interfaces/',
         views.interfaces, name='interfaces'),
    # services
    path('services/', views.service_et_assistance, name='service_et_assistance'),
    path('services/telechargements/', views.telechargement, name='telechargement'),
    path('services/telechargements/2020/patch4/', views.patch4, name='patch4'),
    path('services/faq/', views.faq, name='faq'),
    path('services/presentation/', PresentationView.as_view(),
         name='demande_presentation'),
    path('licence/etudiant/', LicenceEtudiantView.as_view(), name='etudiant'),
    path('licence/educative/', LicenceEtablissementView.as_view(), name='educative'),
    # Blog
    path('actualites/', BlogView.as_view(), name='blog'),
    path('actualites/<slug>', BlogDetailView.as_view(), name='Blog_detail'),

    # Admin
    path('myadmin/', views.dashboard, name='myadmin'),
    path('myadmin/articles/ajouter/',
         AddArticleView.as_view(), name='ajouter-article'),
    path('myadmin/articles/listes',
         ListeArticleView.as_view(), name='listes-articles'),
    path('myadmin/articles/modifier/<slug>',
         EditArticleView.as_view(), name='modifier-article'),
    path('myadmin/articles/supprimer/<slug>',
         DeleteArticleView.as_view(), name='supprimer-article'),
    path('myadmin/categories/', BlogCategoriesCreateView.as_view(), name='categorie'),
    path('myadmin/categories/supprimer/<slug>',
         BlogCategoriesDeleteView.as_view(), name='supprimer-categorie'),
    path('myadmin/categories/modifier/<slug>',
         BlogCategoriesUpdateView.as_view(), name='modifier-categorie'),
    path('myadmin/demander/presentaion/',
         PresentationListView.as_view(), name='presentaion'),
    path('myadmin/licence/etudiant/',
         LicenceEtudiantListView.as_view(), name='etudiant-list'),
    path('myadmin/demander/educative/',
         LicenceEtablissementListView.as_view(), name='educative-list'),
    path('myadmin/video/ajouter/', VideoCreateView.as_view(), name='ajouter-video'),
    path('myadmin/video/modifier/<slug>',
         VideoUpdateView.as_view(), name='modifier-video'),
    path('myadmin/video/supprimer/<slug>',
         VideoDeleteView.as_view(), name='supprimer-video'),
    path('myadmin/video/list/', VideoListView.as_view(), name='list-video'),
    path('myadmin/image/ajouter/',
         GalleryCreateView.as_view(), name='ajouter-image'),
    path('myadmin/image/modifier/<slug>',
         GalleryUpdateView.as_view(), name='modifier-image'),
    path('myadmin/image/supprimer/<slug>',
         GalleryDeleteView.as_view(), name='supprimer-image'),
    path('myadmin/image/list/', GalleryListView.as_view(), name='gallery-list'),


    # Special Froms
    path('journee-utilisateurs-2021/',
         JourneeUtilisateur2021CreateView.as_view(), name="j2021"),
    path('myadmin/list-journee-utilisateur-2021/',
         views.list_subscriber_2021, name="j2021-list"),
    path('formation-armatures-cube/',
         FormationArmaturesCubeCreateView.as_view(), name="formation"),
    path('myadmin/formation/list/',
         FormationArmaturesCubeListView.as_view(), name="fromation_list"),
    path('journee-utilisateurs-2022/',
         JU2022CreateView.as_view(), name="journe22"),
    path('myadmin/list-journee-utilisateur-2022/',
         views.list_subscriber_2022, name="j2022-list"),

    path('initiation-armatures-cube-strakon-plus/',
         JU2022PlusCreateView.as_view(), name="journe22plus"),
    path('myadmin/list-journee-utilisateur-2022-plus/',
         JU2022PlusListView.as_view(), name="j2022plus-list"),

    # Analyse from youtube subscriber
    path('services/presentation/yt/',
         PresentationViewYoutuber.as_view(), name='demande_yt'),
    path('myadmin/demander/presentaion/analyse-youtube/',
         PresentationFromyoutubeListView.as_view(), name='presentaion_yt_list'),

    path('batimat/', BatimatView.as_view(), name='batimat-event'),
    path('myadmin/list-batimat/', BatimatListView.as_view(), name='batimat-event-list')

]
