# Generated by Django 2.1.15 on 2021-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('FR', 'FR'), ('EN', 'EN'), ('DE', 'DE')], max_length=50, verbose_name='Langue de vidéo'),
        ),
    ]
