# Generated by Django 2.1.15 on 2021-05-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_licenceetablissement_licenceetudian_presentation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenceEtudian',
            new_name='LicenceEtudiant',
        ),
        migrations.AlterModelOptions(
            name='licenceetudiant',
            options={'verbose_name': 'Licence Etudiant', 'verbose_name_plural': 'Licence Etudiants'},
        ),
    ]
