# Generated by Django 2.1.15 on 2021-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20210511_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='branche',
            field=models.CharField(choices=[('Ingénieur structurale', 'Ingénieur structurale'), ('Construction préfabriquée', 'Construction préfabriquée'), ('Architecture', 'Architecture'), ("Commerce de l'acier", "Commerce de l'acier"), ("Établissements d'enseignement", "Établissements d'enseignement"), ('Étudiant', 'Étudiant'), ('Autres', 'Autres')], max_length=50, verbose_name='Branche'),
        ),
    ]
