# Generated by Django 2.1.15 on 2021-05-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20210511_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='type_presentation',
            field=models.CharField(choices=[('Présentation du logiciel de CAO STRAKON sur place', 'Présentation du logiciel de CAO STRAKON sur place'), ('Présentation du logiciel de CAO STRAKON via Internet', 'Présentation du logiciel de CAO STRAKON via Internet')], default='via internet', max_length=50, verbose_name='Type de présentation'),
        ),
    ]
