# Generated by Django 2.1.15 on 2021-05-11 23:42

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20210511_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenceetablissement',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',)),
        ),
        migrations.AlterField(
            model_name='licenceetudiant',
            name='certificat',
            field=models.FileField(upload_to='etudian/%Y/%m/%d/', verbose_name="Certificat d'immatriculation ou téléchargement similaire"),
        ),
        migrations.AlterField(
            model_name='licenceetudiant',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',)),
        ),
    ]
