# Generated by Django 2.1.15 on 2021-05-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20210511_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenceetablissement',
            name='commande',
            field=models.CharField(choices=[('Licence', 'Licence'), ('Mise à jour', 'Mise à jour')], default=1, max_length=50, verbose_name='Commandez'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenceetudiant',
            name='commande',
            field=models.CharField(choices=[('Licence', 'Licence'), ('Mise à jour', 'Mise à jour')], default=1, max_length=50, verbose_name='Commandez'),
            preserve_default=False,
        ),
    ]
