# Generated by Django 2.1.15 on 2021-05-12 11:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20210512_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
