# Generated by Django 2.1.15 on 2021-05-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20210512_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/%Y/%m/%d/', verbose_name='Image principale'),
        ),
    ]
