# Generated by Django 2.1.15 on 2021-05-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20210513_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='gallery/%Y/%m/%d/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='video/%Y/%m/%d/', verbose_name='Image principale'),
        ),
    ]
