# Generated by Django 2.1.15 on 2021-05-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20210513_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='code',
            field=models.CharField(default=1, max_length=50, verbose_name='Code YouTube'),
            preserve_default=False,
        ),
    ]
