# Generated by Django 2.1.15 on 2021-05-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20210513_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
    ]
