# Generated by Django 2.1.15 on 2021-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_auto_20210514_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenceetudiant',
            name='ecole',
            field=models.CharField(max_length=200, verbose_name='École / Lieu'),
        ),
    ]
