# Generated by Django 2.1.15 on 2021-05-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_auto_20210518_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenceetudiant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Votre nom'),
        ),
    ]
