# Generated by Django 2.1.15 on 2021-05-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_auto_20210518_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('FR', 'FR'), ('EN', 'EN'), ('DE', 'DE')], default='FR', max_length=50, verbose_name='Langue de la vidéo'),
        ),
    ]
