# Generated by Django 2.1.15 on 2021-06-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_auto_20210518_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneeUtilisateur2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nom_de_societe', models.CharField(max_length=200, verbose_name='Nom de la société')),
                ('contact', models.CharField(max_length=200, verbose_name='Personne contact')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('accompagnee', models.CharField(max_length=200, verbose_name='Accompagnée de')),
            ],
            options={
                'verbose_name': 'Journée Utilisateurs 2021',
                'verbose_name_plural': 'Journée Utilisateurs 2021',
            },
        ),
    ]
