# Generated by Django 2.1.15 on 2021-06-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_journeeutilisateur2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeeutilisateur2021',
            name='selected_date',
            field=models.CharField(choices=[('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22')], default='18', max_length=5, verbose_name='Séléctionne une date'),
        ),
    ]
