# Generated by Django 2.1.15 on 2022-03-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_presentationfromyoutube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeeutilisateur2022',
            name='email',
            field=models.CharField(max_length=250, verbose_name='Email'),
        ),
    ]
