# Generated by Django 2.1.15 on 2022-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0034_auto_20220307_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeeutilisateur2022',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='Email'),
        ),
    ]
