# Generated by Django 2.1.15 on 2022-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_auto_20220307_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneeUtilisateur2022plus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nom_de_societe', models.CharField(max_length=200, verbose_name='Nom de la société')),
                ('contact', models.CharField(max_length=200, verbose_name='Personne contact')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('accompagnee', models.CharField(blank=True, max_length=200, null=True, verbose_name='Accompagnée de')),
            ],
            options={
                'verbose_name': 'Journée Utilisateurs 2023',
                'verbose_name_plural': 'Journée Utilisateurs 2023',
            },
        ),
    ]
