# Generated by Django 2.1.15 on 2022-09-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_journeeutilisateur2022plus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journeeutilisateur2022plus',
            options={'verbose_name': 'Journée Utilisateurs 2022+', 'verbose_name_plural': 'Journée Utilisateurs 2022+'},
        ),
    ]
