# Generated by Django 2.1.15 on 2022-09-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_auto_20220916_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeeutilisateur2022plus',
            name='accompagnee',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
