# Generated by Django 2.1.15 on 2022-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0040_batimat_subscryber_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batimat',
            name='subscryber_type',
            field=models.CharField(choices=[('1', 'Particulier'), ('2', 'Étudiant'), ('3', 'Société')], max_length=10, verbose_name="S'inscrire en tant que"),
        ),
    ]
