# Generated by Django 2.1.15 on 2022-09-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0042_auto_20220923_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batimat',
            old_name='societe',
            new_name='nom_ou_societe',
        ),
    ]
