# Generated by Django 2.1.15 on 2022-09-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0043_auto_20220923_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batimat',
            name='nom_ou_societe',
            field=models.CharField(max_length=200, verbose_name='Votre nom complet ou le nom de votre société'),
        ),
    ]
