# Generated by Django 2.1.15 on 2022-09-23 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0044_auto_20220923_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='batimat',
            name='dat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
