# Generated by Django 2.1.15 on 2022-09-23 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0045_batimat_dat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batimat',
            old_name='dat',
            new_name='date',
        ),
    ]
