# Generated by Django 2.1.15 on 2022-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0046_auto_20220923_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batimat',
            name='nom_ou_societe',
            field=models.CharField(max_length=200, verbose_name='Société ou école'),
        ),
        migrations.AlterField(
            model_name='batimat',
            name='subscriber_type',
            field=models.CharField(choices=[('1', 'Particulier'), ('2', 'Étudiant'), ('3', 'Salarié')], max_length=10, verbose_name="S'inscrire en tant que"),
        ),
    ]
