# Generated by Django 2.1.15 on 2022-09-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0047_auto_20220927_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batimat',
            name='nom_ou_societe',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Société ou école'),
        ),
    ]
