# Generated by Django 2.1.15 on 2022-09-28 14:37

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('frontend', '0048_auto_20220927_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='batimat',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batimat',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='state', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
