# Generated by Django 2.1.15 on 2022-05-06 15:36

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Publié')),
                ('name', models.CharField(max_length=250, verbose_name='Titre')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('name',))),
                ('code', models.CharField(max_length=50, verbose_name='Code YouTube')),
                ('category', models.CharField(choices=[('BIM', 'BIM'), ('TIPS', 'Astuse et conseils')], max_length=10, verbose_name='Choisir le catégorie')),
            ],
            options={
                'verbose_name': 'Formation Video',
                'verbose_name_plural': 'Formation Videos',
            },
        ),
    ]
